
import type { Metadata } from "next";
import "./globals.css";
import { Suspense, lazy } from "react";
import ComponentLoader from "@/components/ComponentLoader";

// Lazy load layout components
const Header = lazy(() => import("@/components/layout/Header"));
const Footer = lazy(() => import("@/components/layout/Footer"));

;

// === Metadata ===
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// === Root Layout ===
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` antialiased`}
      >
        <Suspense
          fallback={<ComponentLoader height="h-16" message="Loading header..." />}
        >
          <Header />
        </Suspense>

        <main>{children}</main>

        <Suspense
          fallback={<ComponentLoader height="h-32" message="Loading footer..." />}
        >
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
